# Generated by Django 5.1.6 on 2025-03-11 18:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_aggregate", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Age Group",
                "verbose_name_plural": "Age Groups",
            },
        ),
        migrations.CreateModel(
            name="HDIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_aggregate", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Human Development Index",
                "verbose_name_plural": "Human Development Indices",
            },
        ),
        migrations.CreateModel(
            name="Sex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_aggregate", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Sex",
                "verbose_name_plural": "Sexes",
            },
        ),
        migrations.CreateModel(
            name="DemographicStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "value",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "age_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demographics.agegroup",
                    ),
                ),
                (
                    "hd_index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demographics.hdindex",
                    ),
                ),
                (
                    "sex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demographics.sex",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demographic Statistic",
                "verbose_name_plural": "Demographic Statistics",
                "indexes": [
                    models.Index(fields=["year"], name="demographic_year_2e9c9b_idx"),
                    models.Index(
                        fields=["year", "age_group"], name="demographic_year_9c4c3f_idx"
                    ),
                    models.Index(
                        fields=["year", "sex"], name="demographic_year_5c7aaf_idx"
                    ),
                    models.Index(
                        fields=["year", "hd_index"], name="demographic_year_a8d5bd_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "age_group", "sex", "hd_index"),
                        name="unique_demographic_statistic",
                    )
                ],
            },
        ),
    ]
