name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        
    - name: Generate lock file
      run: |
        poetry lock --no-update
        
    - name: Install dependencies
      run: |
        poetry install --no-root
        
    - name: Lint with Ruff
      run: |
        poetry run ruff check .
        
    - name: Run tests with coverage
      run: |
        poetry run pytest --cov=demographics --cov=visualization --cov-report=term --cov-report=xml
        
    - name: Check coverage threshold
      run: |
        poetry run coverage report --fail-under=80 || echo "Coverage below threshold, but continuing build"
